variable "project_name"   { type = string }
variable "environment"    { type = string }
variable "ami_id"         { type = string }
variable "key_name"       { type = string }
variable "subnet_id"      { type = string }
variable "subnet_ids"     { type = list(string) }
variable "instance_type"  { type = string }
variable "postgres_sg_id" { type = string }
variable "alb_sg_id"      { type = string }
variable "ecs_tasks_sg_id"{ type = string }
variable "vpc_id"         { type = string }
variable "lab_role_arn"   { type = string }